# Generated by Django 4.1.13 on 2024-05-22 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("slider", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slide",
            options={
                "ordering": ["order"],
                "verbose_name": "Slide",
                "verbose_name_plural": "Slides",
            },
        ),
        migrations.AlterField(
            model_name="slide",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slide_images",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="slide",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="slide",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
    ]
